### ISSUE TITLE
一些不符合佣兵等级的项链

### ISSUE THREAD

**Issue by shimizu-yui** [FlashNightModReborn/CrazyFlashNight#2]
地下拳王（lv.5）：生存者军牌（lv.18）
萝丝（lv.11）：生存者军牌（lv.18）
探戈狼（lv.17）：生存者军牌（lv.18）
手好小哦（lv.25）：戌狗项链（lv.30）
诸葛叁（lv.25）：未羊项链（lv.30）
暴君之子（lv.25）：申猴项链（lv.30）
人狼（lv.29）：战斗狂人军牌（lv.35）

**Comment by aka-flashNight** [comment]
已修正
